### ISSUE TITLE
IN_LIST ignores OP quantifier

### ISSUE THREAD

**Issue by rolandmueller** [zaibacu/rita-dsl#76]
Somehow I get this unexpected behaviour when using OP quantifiers (?, *, +, etc) with the IN_LIST element: 
```python
rules = """
list_elements = {"one", "two"}
{IN_LIST(list_elements)?}->MARK("LABEL")
"""
rules = rita.compile_string(rules)
expected_result = "[{'label': 'LABEL', 'pattern': [{'LOWER': {'REGEX': '^(one|two)$'}, 'OP': '?'}]}]"
print("expected_result:", expected_result)
print("result:", rules)
assert str(rules) == expected_result
```
Version: 0.5.0

**Comment by zaibacu** [comment]
Yes, thank you. I actually found the same bug today, so will likely work on it soon

**Comment by rolandmueller** [comment]
Oh cool. Thank you for your great work! I really appreciate it.

**Comment by zaibacu** [comment]
Ok, so fix is in master branch, and in PYPI will come as `0.5.7`version (should be uploaded shortly)
